### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by caarlos0** [caarlos0-graveyard/coverage-maven-plugin#4]
- [x] configuration for avoid breaking the build if coverage is low
- [ ] write more tests [doing]
- [ ] some refactory in tons of classes for sure [doing]
- [x] comment a "-1" in the PR to claim the missing tests
- [ ] choose a license
- [ ] remove old comments when rerun in same pr
- [x] was not considering new files
- [x] deal with multi-module projects [not working as expected.. too many api calls]
- [x] compile in openjdk (tests running in other order breaking all the things)

**Comment by caarlos0** [comment]
refs #16
refs #15
refs #14 
refs #13 
refs #12 
refs #11 
refs #10 
refs #9 
refs #8
